const HAND_TYPES = [
  { name: "High Card",       chips: 5,   mult: 1  },
  { name: "Pair",            chips: 10,  mult: 2  },
  { name: "Two Pair",        chips: 20,  mult: 2  },
  { name: "Three of a Kind", chips: 30,  mult: 3  },
  { name: "Straight",        chips: 30,  mult: 4  },
  { name: "Flush",           chips: 35,  mult: 4  },
  { name: "Full House",      chips: 40,  mult: 4  },
  { name: "Four of a Kind",  chips: 60,  mult: 7  },
  { name: "Straight Flush",  chips: 100, mult: 8  },
  { name: "Five of a Kind",  chips: 120, mult: 12 },
  { name: "Flush House",     chips: 140, mult: 14 },
  { name: "Flush Five",      chips: 160, mult: 16 },
];

const CARD_RANKS = [
  { rank: "2",  chips: 2  },
  { rank: "3",  chips: 3  },
  { rank: "4",  chips: 4  },
  { rank: "5",  chips: 5  },
  { rank: "6",  chips: 6  },
  { rank: "7",  chips: 7  },
  { rank: "8",  chips: 8  },
  { rank: "9",  chips: 9  },
  { rank: "10", chips: 10 },
  { rank: "J",  chips: 10 },
  { rank: "Q",  chips: 10 },
  { rank: "K",  chips: 10 },
  { rank: "A",  chips: 11 },
  { rank: "B",  chips: 50 },
];

const SUITS = ["♠", "♥", "♦", "♣"];

// chips/aMult/xMult: default values (editable in UI)
// chipsStep/aMultStep/xMultStep: input arrow increment — set to per-trigger amount where meaningful
const JOKERS = [
  { name: "Abstract Joker",   chips: 0,   aMult: 3,   xMult: 1,    chipsStep: 1,   aMultStep: 3,    xMultStep: 1,    description: "+3 Mult for each Joker card in hand" },
  { name: "Baron",            chips: 0,   aMult: 0,   xMult: 1.5,  chipsStep: 1,   aMultStep: 1,    xMultStep: 1.5,  description: "Each King held in hand gives x1.5 Mult" },
  { name: "Blackboard",       chips: 0,   aMult: 0,   xMult: 3,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x3 Mult if all held cards are Spades or Clubs" },
  { name: "Blue Joker",       chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 2,   aMultStep: 1,    xMultStep: 1,    description: "+2 Chips per remaining card in deck (enter total manually)" },
  { name: "Bootstraps",       chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 2,    xMultStep: 1,    description: "+2 Mult per $5 you have (enter total manually)" },
  { name: "Brainstorm",       chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "Copies ability of leftmost Joker (enter manually)" },
  { name: "Blueprint",        chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "Copies ability of Joker to the right (enter manually)" },
  { name: "Caino",            chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "Gains x1 Mult each time a face card is destroyed (enter current)" },
  { name: "Card Sharp",       chips: 0,   aMult: 0,   xMult: 3,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x3 Mult if played hand has already been played this round" },
  { name: "Cavendish",        chips: 0,   aMult: 0,   xMult: 3,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x3 Mult" },
  { name: "Clever Joker",     chips: 80,  aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+80 Chips if played hand contains Two Pair" },
  { name: "Constellation",    chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.1,  description: "Gains x0.1 Mult per Planet card used (enter current)" },
  { name: "Crafty Joker",     chips: 80,  aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+80 Chips if played hand contains a Flush" },
  { name: "Crazy Joker",      chips: 0,   aMult: 12,  xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+12 Mult if played hand contains a Straight" },
  { name: "Devious Joker",    chips: 100, aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+100 Chips if played hand contains a Straight" },
  { name: "Droll Joker",      chips: 0,   aMult: 10,  xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+10 Mult if played hand contains a Flush" },
  { name: "Even Steven",      chips: 0,   aMult: 4,   xMult: 1,    chipsStep: 1,   aMultStep: 4,    xMultStep: 1,    description: "+4 Mult when a scored card is even (2,4,6,8,10)" },
  { name: "Fortune Teller",   chips: 0,   aMult: 1,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+1 Mult for Tarot cards used" },
  { name: "Flower Pot",       chips: 0,   aMult: 0,   xMult: 3,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x3 Mult if played hand contains all 4 suits" },
  { name: "Glass Joker",      chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.75, description: "Gains x0.75 Mult per destroyed Glass Card (enter current)" },
  { name: "Green Joker",      chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+1 Mult per hand played, -1 per discard (enter current)" },
  { name: "Half Joker",       chips: 0,   aMult: 20,  xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+20 Mult if played hand contains 3 or fewer cards" },
  { name: "Hologram",         chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.25, description: "Gains x0.25 Mult per card added to deck (enter current)" },
  { name: "Ice Cream",        chips: 100, aMult: 0,   xMult: 1,    chipsStep: 5,   aMultStep: 1,    xMultStep: 1,    description: "+100 Chips (decreases by 5 per hand played; adjust manually)" },
  { name: "Joker",            chips: 0,   aMult: 4,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+4 Mult" },
  { name: "Jolly Joker",      chips: 0,   aMult: 8,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+8 Mult if played hand contains a Pair" },
  { name: "Mad Joker",        chips: 0,   aMult: 10,  xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+10 Mult if played hand contains Two Pair" },
  { name: "Madness",          chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.5,  description: "Gains x0.5 Mult each Blind selected (enter current)" },
  { name: "Mystic Summit",    chips: 0,   aMult: 15,  xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+15 Mult when 0 discards remaining" },
  { name: "Odd Todd",         chips: 31,  aMult: 0,   xMult: 1,    chipsStep: 31,  aMultStep: 1,    xMultStep: 1,    description: "+31 Chips when a scored card is odd (A,3,5,7,9)" },
  { name: "Obelisk",          chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.2,  description: "Gains x0.2 Mult per consecutive non-top-hand played (enter current)" },
  { name: "Photograph",       chips: 0,   aMult: 0,   xMult: 2,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x2 Mult for first played face card each round" },
  { name: "Raised Fist",      chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "Adds 2× rank of lowest card to Mult (enter total manually)" },
  { name: "Runner",           chips: 15,  aMult: 0,   xMult: 1,    chipsStep: 15,  aMultStep: 1,    xMultStep: 1,    description: "Gains +15 Chips if played hand contains a Straight (enter current)" },
  { name: "Scholar",          chips: 20,  aMult: 4,   xMult: 1,    chipsStep: 20,  aMultStep: 4,    xMultStep: 1,    description: "+20 Chips and +4 Mult when Ace is scored" },
  { name: "Shoot the Moon",   chips: 0,   aMult: 13,  xMult: 1,    chipsStep: 1,   aMultStep: 13,   xMultStep: 1,    description: "+13 Mult per Queen held in hand (enter total manually)" },
  { name: "Sly Joker",        chips: 50,  aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+50 Chips if played hand contains a Pair" },
  { name: "Steel Joker",      chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.2,  description: "x0.2 Mult per Steel Card in deck (enter current)" },
  { name: "Stone Joker",      chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 25,  aMultStep: 1,    xMultStep: 1,    description: "+25 Chips per Stone Card in deck (enter total manually)" },
  { name: "Stuntman",         chips: 250, aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+250 Chips, -2 hand size" },
  { name: "The Duo",          chips: 0,   aMult: 0,   xMult: 2,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x2 Mult if played hand contains a Pair" },
  { name: "The Family",       chips: 0,   aMult: 0,   xMult: 4,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x4 Mult if played hand contains Four of a Kind" },
  { name: "The Order",        chips: 0,   aMult: 0,   xMult: 3,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x3 Mult if played hand contains a Straight" },
  { name: "The Tribe",        chips: 0,   aMult: 0,   xMult: 2,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x2 Mult if played hand contains a Flush" },
  { name: "The Trio",         chips: 0,   aMult: 0,   xMult: 3,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "x3 Mult if played hand contains Three of a Kind" },
  { name: "Triboulet",        chips: 0,   aMult: 0,   xMult: 2,    chipsStep: 1,   aMultStep: 1,    xMultStep: 2,    description: "x2 Mult per played King and Queen" },
  { name: "Vampire",          chips: 0,   aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 0.1,  description: "Gains x0.1 Mult per Enhanced card scored (enter current)" },
  { name: "Wily Joker",       chips: 100, aMult: 0,   xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+100 Chips if played hand contains Three of a Kind" },
  { name: "Zany Joker",       chips: 0,   aMult: 12,  xMult: 1,    chipsStep: 1,   aMultStep: 1,    xMultStep: 1,    description: "+12 Mult if played hand contains Three of a Kind" },
];
